### PR TITLE
Add user roles

### PR DESCRIPTION
**Pull request by gameow1124**
Add  login_as_admin in unit_test, 
Add is_admin in the models.
Modify delete function.(Now only admin can delete user.)

### CODE REVIEW

**Comment by gameow1124** [comment]
I can't add is_admin in model like is_authenticated because is_authenticated is import from UserMixin and I can't modify it.

**Comment by amjltc295** [comment]
#20

**Comment by amjltc295** [comment]
This PR is for #20. The user role should be added to User Model instead of check by name.

**Review by amjltc295 — CHANGES_REQUESTED** [review]
This PR is for #20. The user role should be added to User Model instead of checking by name.

**Pull request closed without merging**
